package sop_corba_audio.callbackIntPackage;


/**
* sop_corba_audio/callbackIntPackage/audioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from audio.idl
* Tuesday, June 5, 2018 7:27:40 PM COT
*/

public final class audioHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public audioHolder ()
  {
  }

  public audioHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba_audio.callbackIntPackage.audioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba_audio.callbackIntPackage.audioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba_audio.callbackIntPackage.audioHelper.type ();
  }

}
