package sop_corba_admin.gestionUsuariosIntPackage;

/**
* sop_corba_admin/gestionUsuariosIntPackage/AdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from admin.idl
* Tuesday, June 5, 2018 7:28:26 PM COT
*/

public final class AdminHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba_admin.gestionUsuariosIntPackage.Admin value = null;

  public AdminHolder ()
  {
  }

  public AdminHolder (sop_corba_admin.gestionUsuariosIntPackage.Admin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba_admin.gestionUsuariosIntPackage.AdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba_admin.gestionUsuariosIntPackage.AdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba_admin.gestionUsuariosIntPackage.AdminHelper.type ();
  }

}
