package sop_corba_admin.gestionUsuariosIntPackage;


/**
* sop_corba_admin/gestionUsuariosIntPackage/Admin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from admin.idl
* Tuesday, June 5, 2018 7:28:26 PM COT
*/

public final class Admin implements org.omg.CORBA.portable.IDLEntity
{
  public String login = null;
  public String clave = null;

  public Admin ()
  {
  } // ctor

  public Admin (String _login, String _clave)
  {
    login = _login;
    clave = _clave;
  } // ctor

} // class Admin
