package sop_corba_admin.gestionUsuariosIntPackage;


/**
* sop_corba_admin/gestionUsuariosIntPackage/ListaUsuariosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from admin.idl
* Tuesday, June 5, 2018 7:28:26 PM COT
*/

public final class ListaUsuariosHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba_admin.gestionUsuariosIntPackage.Usuario value[] = null;

  public ListaUsuariosHolder ()
  {
  }

  public ListaUsuariosHolder (sop_corba_admin.gestionUsuariosIntPackage.Usuario[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba_admin.gestionUsuariosIntPackage.ListaUsuariosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba_admin.gestionUsuariosIntPackage.ListaUsuariosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba_admin.gestionUsuariosIntPackage.ListaUsuariosHelper.type ();
  }

}
