package sop_corba_admin.gestionUsuariosIntPackage;


/**
* sop_corba_admin/gestionUsuariosIntPackage/Usuario.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from admin.idl
* Tuesday, June 5, 2018 7:28:26 PM COT
*/

public final class Usuario implements org.omg.CORBA.portable.IDLEntity
{
  public String nombres = null;
  public String apellidos = null;
  public String nickName = null;
  public String clave = null;

  public Usuario ()
  {
  } // ctor

  public Usuario (String _nombres, String _apellidos, String _nickName, String _clave)
  {
    nombres = _nombres;
    apellidos = _apellidos;
    nickName = _nickName;
    clave = _clave;
  } // ctor

} // class Usuario
