package sop_corba_admin;


/**
* sop_corba_admin/gestionUsuariosInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from admin.idl
* Tuesday, June 5, 2018 7:28:26 PM COT
*/

public interface gestionUsuariosInt extends gestionUsuariosIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface gestionUsuariosInt
