package sop_corba_admin;

/**
* sop_corba_admin/gestionUsuariosIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from admin.idl
* Tuesday, June 5, 2018 7:28:26 PM COT
*/

public final class gestionUsuariosIntHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba_admin.gestionUsuariosInt value = null;

  public gestionUsuariosIntHolder ()
  {
  }

  public gestionUsuariosIntHolder (sop_corba_admin.gestionUsuariosInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba_admin.gestionUsuariosIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba_admin.gestionUsuariosIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba_admin.gestionUsuariosIntHelper.type ();
  }

}
