package sop_corba_admin;


/**
* sop_corba_admin/gestionUsuariosIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from admin.idl
* Tuesday, June 5, 2018 7:28:26 PM COT
*/

public abstract class gestionUsuariosIntPOA extends org.omg.PortableServer.Servant
 implements sop_corba_admin.gestionUsuariosIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ingresoSistemaAdmin", new java.lang.Integer (0));
    _methods.put ("registroUsuario", new java.lang.Integer (1));
    _methods.put ("listarUsuarios", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba_admin/gestionUsuariosInt/ingresoSistemaAdmin
       {
         String login = in.read_string ();
         String clave = in.read_string ();
         boolean $result = false;
         $result = this.ingresoSistemaAdmin (login, clave);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // sop_corba_admin/gestionUsuariosInt/registroUsuario
       {
         sop_corba_admin.gestionUsuariosIntPackage.Usuario usuario = sop_corba_admin.gestionUsuariosIntPackage.UsuarioHelper.read (in);
         boolean $result = false;
         $result = this.registroUsuario (usuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // sop_corba_admin/gestionUsuariosInt/listarUsuarios
       {
         sop_corba_admin.gestionUsuariosIntPackage.Usuario $result[] = null;
         $result = this.listarUsuarios ();
         out = $rh.createReply();
         sop_corba_admin.gestionUsuariosIntPackage.ListaUsuariosHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba_admin/gestionUsuariosInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public gestionUsuariosInt _this() 
  {
    return gestionUsuariosIntHelper.narrow(
    super._this_object());
  }

  public gestionUsuariosInt _this(org.omg.CORBA.ORB orb) 
  {
    return gestionUsuariosIntHelper.narrow(
    super._this_object(orb));
  }


} // class gestionUsuariosIntPOA
