package sop_corba_admin;


/**
* sop_corba_admin/gestionUsuariosIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from admin.idl
* Tuesday, June 5, 2018 7:28:26 PM COT
*/

public interface gestionUsuariosIntOperations 
{
  boolean ingresoSistemaAdmin (String login, String clave);
  boolean registroUsuario (sop_corba_admin.gestionUsuariosIntPackage.Usuario usuario);
  sop_corba_admin.gestionUsuariosIntPackage.Usuario[] listarUsuarios ();
} // interface gestionUsuariosIntOperations
