package sop_corba_audio;

/**
* sop_corba_audio/callbackIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from audio.idl
* Tuesday, June 5, 2018 7:27:40 PM COT
*/

public final class callbackIntHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba_audio.callbackInt value = null;

  public callbackIntHolder ()
  {
  }

  public callbackIntHolder (sop_corba_audio.callbackInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba_audio.callbackIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba_audio.callbackIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba_audio.callbackIntHelper.type ();
  }

}
