package sop_corba_audio;


/**
* sop_corba_audio/callbackIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from audio.idl
* Sunday, June 10, 2018 11:24:40 AM COT
*/

public interface callbackIntOperations 
{
  void recibirAudio (byte[] audioStream);
} // interface callbackIntOperations
