package sop_corba_audio;


/**
* sop_corba_audio/servidorAudio.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from audio.idl
* Sunday, June 10, 2018 11:24:40 AM COT
*/

public interface servidorAudio extends servidorAudioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface servidorAudio
