package sop_corba_audio;


/**
* sop_corba_audio/servidorAudioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from audio.idl
* Tuesday, June 5, 2018 7:27:40 PM COT
*/

public interface servidorAudioOperations 
{
  void enviarAudio (byte[] audioStream);
  boolean ingresoSistemaUsuario (String nickName, String clave);
  boolean registrarUsuario (sop_corba_audio.callbackInt callback);
} // interface servidorAudioOperations
