package sop_corba_audio;


/**
* sop_corba_audio/servidorAudioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from audio.idl
* Sunday, June 10, 2018 11:24:40 AM COT
*/

public interface servidorAudioOperations 
{
  void enviarAudio (byte[] audioStream);
  boolean ingresoSistemaUsuario (String nickName, String clave);
  boolean registrarUsuario (sop_corba_audio.callbackInt callback);
  boolean suscribirUsuario (String nickName);
} // interface servidorAudioOperations
