package sop_corba_audio;


/**
* sop_corba_audio/servidorAudio.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from audio.idl
* Tuesday, June 5, 2018 7:27:40 PM COT
*/

public interface servidorAudio extends servidorAudioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface servidorAudio
