module sop_corba_audio{

  interface callbackInt;

  interface servidorAudio{
    typedef sequence<octet> audio;
    void enviarAudio(in audio audioStream);
    boolean ingresoSistemaUsuario(in string nickName, in string clave);
    boolean registrarUsuario(in callbackInt callback);
    boolean suscribirUsuario(in string nickName);
  };

  interface callbackInt{
    typedef sequence<octet> audio;
    void recibirAudio(in audio audioStream);
  };

};
